services:
  frontend:
    container_name: tlias-frontend
    build:
      context: ./vue-tlias-management
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      BACKEND_URL: "http://host.docker.internal:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
